# Generated by Django 3.0.2 on 2020-01-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='exam_id',
            new_name='exam',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='result',
            name='score',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
